### ISSUE TITLE
zstor storage overhead and when the data is flushed to the remote zdbs

### ISSUE THREAD

**Issue by OmarElawady** [threefoldfoundation/info_manual3#13]
When is the data flushed to the remote zdbs and is it configurable? And is there a way to force flush to implement a proper graceful shutdown?

I executed `dd if=/dev/zero of=hi bs=$((500 * 1024)) count=$((1024))` then `dd if=/dev/zero of=hi bs=$((500)) count=$((1024 * 1024))` and the container rootfs size is 3.8G and the file is still at about 100MB. So is there a way to know how big should the container be to avoid filling the disk space depending on the zdb size i have (and possibly the config that specifies when to flush the data, if there's one)?
Context: qsfs (zdbfs+zdb+zstor) is added into a single container to mount the qsfs, and it starts with a limit on its disk size

**Comment by maxux** [comment]
The `--datasize <bytes>` parameter set the datafile size, when a datafile is full, upload is triggered
The `--rotate <secs>` force rotation after that amount of seconds

There is no graceful shutdown upload because file is only uploaded when they are immuable (full), a shutdown doesn't make the file immuable.

**Comment by OmarElawady** [comment]
The `close` hook was used to upload the mutable (active) datafile and the last active index for each namespace, so container restarts goes back to the exact same state.

After https://github.com/threefoldtech/0-stor_v2/pull/80, the big disk consumption doesn't happen anymore (don't know what was its cause).
