### ISSUE TITLE
Add requirements to manual section in library

### ISSUE THREAD

**Issue by sabrinasadik** [threefoldfoundation/info_manual3#46]
Information is spread across wiki and Forum. The only thing that we know all farmers go through is the manual. The manual should have information to avoid complaints and confusion afterward.

1. HW requirements 
2. Uptime requirements

**Comment by despiegk** [comment]
linking to main wiki is good enough probably, because dumping everything in manual is not a solution
everything to do with how farming works is in main wiki

lets put links for now

**Comment by sasha-astiadi** [comment]
@scottyeager do you know if these pages existed? i will link them on manual sidebar

**Comment by scottyeager** [comment]
The [DIY guide](https://library.threefold.me/info/threefold#/tfgrid/farming/threefold__diy_guide) specifies hardware requirements. While the 500gb minimum SSD size is a good guideline, in reality the minimum is 50gb per CU for purposes of farming rewards, and Zos also reserves 100gb of SSD as cache. Not sure what happens if a node is booted with less than 100gb SSD.

I didn't find any references to the uptime requirement in the wiki.

**Comment by sasha-astiadi** [comment]
i found https://library.threefold.me/info/threefold#/manual__faq?id=what-is-the-necessary-uptime-for-a-3node-per-period-of-one-month no farming FAQ for uptime requirement. so ill close this issue unless more in necessary. as we have nboth linked already on sidebar. i am now adding faq to sidebar
