### ISSUE TITLE
Add section for gettft

### ISSUE THREAD

**Issue by xmonader** [threefoldfoundation/info_manual3#48]
add docs for gettft and how to do buy with fiat

**Comment by nbabenko** [comment]
Updates to the library regarding GETTFT.com
https://github.com/threefoldfoundation/info_threefold_pub/commit/72da26fa366cc9b9654cc19dbbab06ef7402bc39
https://github.com/threefoldfoundation/info_threefold_pub/commit/e461e96447826e5f28dd787a112f5513cac25882

Detailed manual on GETTFT we decided not to write down since GETTFT.COM is mostly self-explanatory.
